### PR TITLE
Deflake SshSlavesPluginTest

### LINKED ISSUE #866: plugins.SshSlavesPluginTest.newAgent fails
Named test fails with https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/master/524/testReport/junit/plugins/SshSlavesPluginTest/java_11_jenkins_latest_split4___newAgent/ on the default branch.

### PR DESCRIPTION
**Pull request by jtnord**
clicking on something produces some asynchronous change and the result
may or may not be present by the time we then try to do something.

instead of assuming the click immediately produces a result we wait for
the expect result before then interacting with it.

Fixes #866

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

File: src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java [hunk 1]
```diff
@@ -36,14 +36,11 @@ public SshCredentialDialog addCredential() {
 
         find(by.button("Add")).click();
 
-        if (getElement(by.xpath("//span[contains(@class,'credentials-add')]")) == null) {
+        String providerXpathExpr = "//div[contains(@class,'credentials-add-menu-items')]"
```
Comment (jtnord) [inline src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java:39]: this could probably be cleaned up given we are supporting 2.346 LTS and weeklies, but as this is blocking important fixes I am leaving it as is for now.

File: src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java [hunk 2]
```diff
@@ -36,14 +36,11 @@ public SshCredentialDialog addCredential() {
...
+                + "/div[@class='bd']/ul[@class='first-of-type']/li[contains(@class, 'yuimenuitem')]"
+                + "/span[contains(@class,'yuimenuitemlabel') and contains(@title, 'Jenkins Credentials Provider')]";
 
-            String providerXpathExpr = "//div[contains(@class,'credentials-add-menu-items')]"
-                    + "/div[@class='bd']/ul[@class='first-of-type']/li[contains(@class, 'yuimenuitem')]"
-                    + "/span[contains(@class,'yuimenuitemlabel') and contains(@title, 'Jenkins Credentials Provider')]";
-
-            find(by.xpath(providerXpathExpr)).click();
-        }
+        waitFor(by.xpath(providerXpathExpr)).click();
```
Comment (jtnord) [inline src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java:43]: switch to wait for so we know the "Jenkins Credentials Provider" button is visible before clicking it.

it would seem logical to me that the addition of new credentials should be part of a credentials page area but a quick scan did not show anything immediately obvious.

**Review by NotMyFault — APPROVED** [review]
Nice, thanks for addressing 👍🏻

**Comment by jtnord** [comment]
well that didn't work as I expected 😢

**Comment by jtnord** [comment]
interestingly 2 test failures here.  
Locally I can "mostly" reporoduce `plugins.SshSlavesPluginTest.connectWithKey`
```Element <select class="jenkins-select__input validated select  credentials-select" name="_.credentialsId"> is not clickable at point (934,386) because another element <div class="jenkins-form-item tr "> obscures it```

but for me it is the breadcrumb bar (`<ul id="breadcrumbs">`) that obscure it.  the scrolling into view is working, but the scrolling as not finished but the time we try and interact with the element :-/

**Comment by jtnord** [comment]
> interestingly 2 test failures here. Locally I can "mostly" reporoduce `plugins.SshSlavesPluginTest.connectWithKey` `Element <select class="jenkins-select__input validated select credentials-select" name="_.credentialsId"> is not clickable at point (934,386) because another element <div class="jenkins-form-item tr "> obscures it`
> 
> but for me it is the breadcrumb bar (`<ul id="breadcrumbs">`) that obscure it. the scrolling into view is working, but the scrolling as not finished but the time we try and interact with the element :-/

should be fixed fixed in https://github.com/jenkinsci/acceptance-test-harness/pull/894/commits/a0bbd06a382e9903b6d795daaba18f24432fca44#diff-3a4cafd06934f5a6601e38773ca906e25d33fe5e7b4acf7992a7e71875d5d994R45-R48
